_wandb:
    value:
        cli_version: 0.21.0
        e:
            cgpxuenqjra2jv3jj4cdh0pnmbujm4u3:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Unknown
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "5368709120"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "466565414912"
                email: ayoubelma549@gmail.com
                executable: /opt/anaconda3/envs/myven/bin/python
                git:
                    commit: 0b87c6a758825e31d4bf7fdf44d820c42cc1f17d
                    remote: https://github.com/ayoubGL/BankTermSubscription_prediction.git
                host: fvfgh3kyq05p.klientdrift.uib.no
                memory:
                    total: "17179869184"
                os: macOS-15.3.1-x86_64-i386-64bit
                program: /Users/ayoub/Desktop/PhDCourses/courses/ML_classifier/BankTermPrediction/main.py
                python: CPython 3.11.13
                root: /Users/ayoub/Desktop/PhDCourses/courses/ML_classifier/BankTermPrediction
                startedAt: "2025-07-06T14:51:16.655967Z"
                writerId: cgpxuenqjra2jv3jj4cdh0pnmbujm4u3
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-x86_64
class_weight:
    value: balanced
max_depth:
    value: 10
min_samples_leaf:
    value: 3
min_samples_split:
    value: 5
model_type:
    value: RandomForestClassifier
n_estimators:
    value: 200
